version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_product
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_seller
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: fact_sales
    columns:
      - name: order_id
        tests:
          - not_null